apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
  namespace: dib-c1
  labels:
    app: nginx-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 8090
      targetPort: 8090
      name: app
  selector:
    app: nginx-frontend
