# mdm — 主数据管理
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdm
  namespace: c1-idc-test
  labels:
    app: mdm
    tier: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdm
  template:
    metadata:
      labels:
        app: mdm
        tier: platform
    spec:
      imagePullSecrets:
        - name: dib-registry-secret
      containers:
        - name: mdm
          image: 10.0.6.183:8088/c1/platform-mdm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 20002
              name: http
              protocol: TCP
          env:
            - name: C1_ENV
              valueFrom:
                configMapKeyRef:
                  name: dib-common-config
                  key: C1_ENV
            - name: TZ
              value: "Asia/Shanghai"
          envFrom:
            - configMapRef:
                name: dib-common-config

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - name: app-logs
              mountPath: /opt/app/logs
            - name: fonts
              mountPath: /usr/share/fonts
              readOnly: true
          livenessProbe:
            httpGet:
              path: /api/mdm/actuator/health
              port: 20002
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/mdm/actuator/health
              port: 20002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: fonts
          hostPath:
            path: /usr/share/fonts
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mdm
  namespace: c1-idc-test
  labels:
    app: mdm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 20002
      targetPort: 20002
      protocol: TCP
  selector:
    app: mdm
