apiVersion: v1
kind: Secret
metadata:
  name: dib-c1-db-secret
  namespace: dib-c1
type: Opaque
stringData:
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "CHANGE_ME"             # TODO: 按实际填写
  OPENGAUSS_USERNAME: "gaussdb"
  OPENGAUSS_PASSWORD: "CHANGE_ME"         # TODO: 按实际填写
