services:
  ########## Docker可视化管理工具 ##########
  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    ports:
      - "9443:943"
    environment:
      - ADMIN_USER=dib
      - ADMIN_PASSWORD=dib@123456789
    volumes:
      - /opt/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped