apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-data
  namespace: dib-c1
  labels:
    app: service-data
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-data
  template:
    metadata:
      labels:
        app: service-data
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "30003"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: service-data
          image: hub.dibtime.com/dib-c1/c1-data:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30003
              name: http
          env:
            - name: C1_ENV
              value: "k8s"
            # Nacos
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  name: dib-c1-config
                  key: NACOS_SERVER_ADDR
            - name: SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: dib-c1-config
                  key: NACOS_NAMESPACE
            - name: SPRING_CLOUD_NACOS_DISCOVERY_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dib-c1-config
                  key: NACOS_USERNAME
            - name: SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dib-c1-nacos-secret
                  key: NACOS_PASSWORD
            # Redis
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: dib-c1-config
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: dib-c1-config
                  key: REDIS_PORT
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dib-c1-redis-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "5Gi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 30003
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 30003
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: app-logs
              mountPath: /opt/app/logs
      volumes:
        - name: app-logs
          emptyDir: {}
      imagePullSecrets:
        - name: harbor-registry-secret
