#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    proxy_read_timeout 60s;


    # 开启 gzip 压缩
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss;
    gzip_min_length 1024;
    gzip_comp_level 6;
    gzip_vary on;


    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }

    # c1
    server {
        listen 8090;
        index index.html index.htm;

        # 重定向到 report 服务
        location = / {
            return 301 /app-report/;
        }

        location / {
            root /opt/app/c1-client;
        }
        
        location /api-oauth/ {
            client_max_body_size 200m;
            proxy_pass http://platform-gateway:20000/api-oauth/;
        }

        location /api/auth/ {
            client_max_body_size 200m;
            proxy_pass http://platform-gateway:20000/api/auth/;
        }

        location /api/mdm/ {
            client_max_body_size 200m;
            proxy_pass http://platform-gateway:20000/api/mdm/;
        }
        
        location /api/extract/ {
            client_max_body_size 200m;
            proxy_pass http://platform-gateway:20000/api/extract/;
        }

        location /api/report/ {
            client_max_body_size 200m;
            proxy_pass http://platform-gateway:20000/api/report/;
        }
        
        location /api/data/ {
            client_max_body_size 200m;
            proxy_pass http://platform-gateway:20000/api/data/;
        }

        location /api/rule/ {
            client_max_body_size 200m;
            proxy_pass http://platform-gateway:20000/api/rule/;
        }

        location /sso/ {
            client_max_body_size 200m;
            proxy_pass http://myhost:9090/sso/;
        }
        error_page 504 /custom_504.html;

        location = /custom_504.html {
            internal;
            default_type text/plain;
            return 504 '抱歉，您的请求未能及时得到响应。请稍后刷新查看执行结果！';
        }

        location @router {
            rewrite ^.*$ /index.html last;        
        }

    }

}