apiVersion: v1
kind: Service
metadata:
  name: mdm
  namespace: dib-c1
  labels:
    app: mdm
spec:
  type: ClusterIP
  ports:
    - port: 20002
      targetPort: 20002
      protocol: TCP
      name: http
  selector:
    app: mdm
