input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "[event][original]" => "%{TIMESTAMP_ISO8601:log_timestamp}%{SPACE}%{LOGLEVEL:level}%{SPACE}%{POSINT:pid}%{SPACE}---%{SPACE}\[%{DATA:thread_name}\]%{SPACE}%{DATA:classname}%{SPACE}:%{SPACE}%{GREEDYDATA:message}"
    }
    tag_on_failure => ["_grokparsefailure"]
    overwrite => ["message"]
  }

  date {
    match => ["log_timestamp", "yyyy-MM-dd HH:mm:ss.SSS"]
    target => "@timestamp"
    timezone => "Asia/Shanghai"
  }

  mutate {
    remove_field => ["log_timestamp"]
    lowercase => ["level"]
    convert => {
      "pid" => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://10.0.5.239:9200"]
    index => "%{[fields][product]}-logs-%{[fields][env]}-%{[fields][app]}-%{+YYYY.MM.dd}"
  }
}