apiVersion: v1
kind: Service
metadata:
  name: service-rule
  namespace: dib-c1
  labels:
    app: service-rule
spec:
  type: ClusterIP
  ports:
    - port: 30004
      targetPort: 30004
      protocol: TCP
      name: http
  selector:
    app: service-rule
