apiVersion: v1
kind: Service
metadata:
  name: c1-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: c1-prometheus
spec:
  type: ClusterIP
  selector:
    app: c1-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
