# data-dg — 数据治理
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-dg
  namespace: c1-idc-test
  labels:
    app: data-dg
    tier: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-dg
  template:
    metadata:
      labels:
        app: data-dg
        tier: business
    spec:
      imagePullSecrets:
        - name: dib-registry-secret
      containers:
        - name: data-dg
          image: 10.0.6.183:8088/c1/c1-dg:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30005
              name: http
              protocol: TCP
          env:
            - name: C1_ENV
              valueFrom:
                configMapKeyRef:
                  name: dib-common-config
                  key: C1_ENV
            - name: TZ
              value: "Asia/Shanghai"
          envFrom:
            - configMapRef:
                name: dib-common-config

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1536Mi"
          volumeMounts:
            - name: app-logs
              mountPath: /opt/app/logs
            - name: fonts
              mountPath: /usr/share/fonts
              readOnly: true
          livenessProbe:
            httpGet:
              path: /api/dg/actuator/health
              port: 30005
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/dg/actuator/health
              port: 30005
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: fonts
          hostPath:
            path: /usr/share/fonts
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: data-dg
  namespace: c1-idc-test
  labels:
    app: data-dg
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 30005
      targetPort: 30005
      protocol: TCP
  selector:
    app: data-dg
