apiVersion: v1
kind: Secret
metadata:
  name: dib-registry-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dib.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.registry.server .Values.registry.username .Values.registry.password .Values.registry.email (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc | quote }}
